plugins {
    id("java")
    id("maven-publish")
    id("fabric-loom") version "1.9.2" apply(false)
    id("babric-loom-extension") version "1.9.4" apply(false)
    id("com.github.johnrengelman.shadow") version "${shadow_version}"
}


tasks.register('cleanAll', GradleBuild) {
    group = 'voicechat'
    tasks = [
            ':common:clean',
            ':api:clean',
            ':forge:clean',
            ':bukkit:clean',
    ]
}
tasks.register('runFabricClient', GradleBuild) {
    group = 'voicechat'
    tasks = [
            ':fabric_client:runClient'
    ]
}
tasks.register('runFabricServer', GradleBuild) {
    group = 'voicechat'
    tasks = [
            ':fabric_client:runServer'
    ]
}
tasks.register('buildAll', GradleBuild) {
    group = 'voicechat'
    tasks = [
            ':fabric_client:build',
            ':fabric_server:build',
    ]
}