pluginManagement {
    repositories {
        maven { url = "https://maven.fabricmc.net/" }
        maven { url = "https://maven.glass-launcher.net/babric/" }
        maven { url = 'https://maven.minecraftforge.net/' }
        maven { url = 'https://maven.maxhenkel.de/repository/public' }
        maven { url = "https://maven.glass-launcher.net/releases/" }
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = 'voicechat'
include('api', 'common_client', 'common', 'fabric_client', 'fabric_server')